name: Release

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: gradle

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Build 1.16 version
        run: ./gradlew :toomanybinds-wrapper:build116 --stacktrace

      - name: Build 1.17 version
        run: ./gradlew :toomanybinds-wrapper:build117 --stacktrace

      - name: Build 1.18.2 version
        run: ./gradlew :toomanybinds-wrapper:build1182 --stacktrace

      - name: Build 1.19 version
        run: ./gradlew :toomanybinds-wrapper:build119 --stacktrace

      - name: Publish 1.16 version
        uses: Kir-Antipov/mc-publish@v3.1
        with:
          modrinth-id: 548fsydf
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          curseforge-id: 412915
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          files-primary: toomanybinds-wrapper/build/libs/*+1.16!(*-@(dev|sources)).jar
          name: Too Many Binds 0.3.2 for 1.16
          version: 0.3.2+1.16
          version-type: release
          loaders: |
            fabric
          dependencies: |
            fabric-api    | depends
            cloth-config  | depends
            amecs         | depends
            modmenu       | recommends

      - name: Publish 1.17 version
        uses: Kir-Antipov/mc-publish@v3.1
        with:
          modrinth-id: 548fsydf
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          curseforge-id: 412915
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          files-primary: toomanybinds-wrapper/build/libs/*+1.17!(*-@(dev|sources)).jar
          name: Too Many Binds 0.3.2 for 1.17 to 1.18.1
          version: 0.3.2+1.17
          version-type: release
          loaders: |
            fabric
          game-versions: |
            1.17
            1.17.1
            1.18
            1.18.1
          dependencies: |
            fabric-api    | depends
            cloth-config  | depends
            amecs         | depends
            modmenu       | recommends

      - name: Publish 1.18.2 version
        uses: Kir-Antipov/mc-publish@v3.1
        with:
          modrinth-id: 548fsydf
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          curseforge-id: 412915
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          files-primary: toomanybinds-wrapper/build/libs/*+1.18.2!(*-@(dev|sources)).jar
          name: Too Many Binds 0.3.2 for 1.18.2
          version: 0.3.2+1.18.2
          version-type: release
          loaders: |
            fabric
          dependencies: |
            fabric-api    | depends
            cloth-config  | depends
            amecs         | depends
            modmenu       | recommends

      - name: Publish 1.19 version
        uses: Kir-Antipov/mc-publish@v3.1
        with:
          modrinth-id: 548fsydf
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          curseforge-id: 412915
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          files-primary: toomanybinds-wrapper/build/libs/*+1.19!(*-@(dev|sources)).jar
          name: Too Many Binds 0.3.2 for 1.19
          version: 0.3.2+1.19
          version-type: release
          loaders: |
            fabric
          dependencies: |
            fabric-api    | depends
            cloth-config  | depends
            amecs         | depends
            modmenu       | recommends

